# Generated by Django 5.0.4 on 2024-12-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_book_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_cauntry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
