# Generated by Django 5.0.4 on 2024-12-01 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_book_author_cauntry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author_cauntry',
        ),
    ]
