# Generated by Django 5.0.4 on 2024-12-10 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_book_author_cauntry'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
