# Generated by Django 5.0.4 on 2024-05-09 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_author_picture_alter_book_image'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.book'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(choices=[('Viloyatni tanlang', 'Viloyatni tanlang'), ('tashkent', 'Toshkent shahar'), ('andijon', 'Andijon viloyati'), ('buxoro', 'Buxoro viloyati'), ('fargona', "Farg'ona viloyati"), ('jizzax', 'Jizzax viloyati'), ('namangan', 'Namangan viloyati'), ('navoiy', 'Navoiy viloyati'), ('qashqadaryo', 'Qashqadaryo viloyati'), ('qoraqalpogiston', "Qoraqalpog'iston Respublika"), ('samarqand', 'Samarqand viloyati'), ('sirdaryo', 'Sirdaryo viloyati'), ('surxondaryo', 'Surxondaryo viloyati'), ('toshkent', 'Toshkent viloyati'), ('xorazm', 'Xorazm viloyati')], max_length=17),
        ),
    ]
